baseURL: /
params:
  palette: yellow
  domain: 'https://galeriebyalexia-84029.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
title: Galerie_by_alexia
