baseURL: /
params:
  palette: yellow
  domain: 'https://galeriebyalexia-84029.netlify.app'
  header:
    title: lorem-ipsum
    tagline: lorem-ipsum
    logo_img_alt: lorem-ipsum
    has_nav: true
    nav_links: []
    has_social: true
    social_links: []
    type: header
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
title: Galerie_by_alexia
